"use client";
import { useCallback, useEffect, useRef, useState } from "react";

type Opp={symbol:string;score:number;action:string;category?:string;confidence:number;entry:number|null;stopLoss:number|null;tp1:number|null;tp2:number|null;riskReward:number|null;reasons:string[];warnings?:string[];direction?:string;changePct?:number;liquidity?:number;price?:number};
type Brief={symbol:string;changePct:number;price:number;quoteVolume?:number};
type Pump={symbol:string;price:number;changePct:number};
type SignalFilter="ALL"|"BUY"|"SELL";
const fmt=(v:number|null|undefined)=>v==null||Number.isNaN(v)?"—":v.toLocaleString("en-US",{maximumFractionDigits:6});
const catLabel:Record<string,string>={STRONG_BUY:"🔥 خرید قوی",BUY_CANDIDATE:"🟢 نامزد خرید",BUY:"🟢 خرید",STRONG_SELL:"🔻 فروش قوی",SELL_CANDIDATE:"🔴 نامزد فروش",SELL:"🔴 فروش",PUMP_WATCH:"🚀 پایش پامپ",WAIT:"🟡 انتظار",AVOID:"⛔ اجتناب",HIGH_RISK:"⚠️ ریسک بالا"};
const withTimeout=async(url:string,ms=12000)=>{const c=new AbortController();const t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{cache:"no-store",signal:c.signal});if(!r.ok)throw new Error(`${url}: HTTP ${r.status}`);return await r.json()}finally{clearTimeout(t)}};
export default function Home(){
 const[items,setItems]=useState<Opp[]>([]),[pumps,setPumps]=useState<Pump[]>([]),[majors,setMajors]=useState<Brief[]>([]),[gainers,setGainers]=useState<Brief[]>([]),[losers,setLosers]=useState<Brief[]>([]),[updated,setUpdated]=useState(""),[loading,setLoading]=useState(true),[live,setLive]=useState(false),[message,setMessage]=useState(""),[source,setSource]=useState(""),[showHelp,setShowHelp]=useState(false),[signalFilter,setSignalFilter]=useState<SignalFilter>("ALL");
 const busy=useRef(false);
 const load=useCallback(async()=>{if(busy.current)return;busy.current=true;setLoading(true);setMessage("");try{const results=await Promise.allSettled([withTimeout("/api/opportunities",12000),withTimeout("/api/market",8000),withTimeout("/api/pump-watch",8000)]);const[oppR,marketR,pumpR]=results;let ok=0;if(oppR.status==="fulfilled"){const o=oppR.value;setItems(o.opportunities||[]);setUpdated(o.updatedAt||"");setLive(Boolean(o.live));setMessage(o.message||"");setSource(o.source||"");ok++}if(marketR.status==="fulfilled"){const m=marketR.value;setMajors(m.majors||[]);setGainers(m.gainers||[]);setLosers(m.losers||[]);ok++}if(pumpR.status==="fulfilled"){setPumps(pumpR.value.items||[]);ok++}if(ok===0){setLive(false);setMessage("دریافت داده از تبدیل در زمان مقرر انجام نشد. دوباره تلاش کنید.")}else if(ok<3){setMessage("بخشی از داده‌های تبدیل دریافت شد؛ بخش باقی‌مانده در بروزرسانی بعدی تکمیل می‌شود.")}}catch(e){setLive(false);setMessage(e instanceof Error?e.message:"خطای دریافت داده") }finally{setLoading(false);busy.current=false}},[]);
 useEffect(()=>{load();const t=setInterval(load,90000);return()=>clearInterval(t)},[load]);
 const risks=items.filter(o=>["STRONG_SELL","SELL_CANDIDATE","AVOID","HIGH_RISK"].includes(o.category||o.action));
 const buySignals=items.filter(o=>["STRONG_BUY","BUY_CANDIDATE","BUY"].includes(o.category||o.action)||o.direction==="BUY");
 const sellSignals=items.filter(o=>["STRONG_SELL","SELL_CANDIDATE","SELL","AVOID","HIGH_RISK"].includes(o.category||o.action)||o.direction==="SELL");
 const displayed=signalFilter==="BUY"?buySignals:signalFilter==="SELL"?sellSignals:items;
 return <main dir="rtl"><div className="shell"><header><div><span className="badge">PACT-OS · AI Crypto Assistant</span><h1>🔥 بهترین فرصت‌های فعلی</h1><p>دستیار تصمیم‌گیری — اسکن زنده بازار، بدون معامله خودکار و بدون تضمین سود</p></div><div className="header-actions"><div className={live?"status live":"status"}>● {live?`داده زنده${source?` (${source})`:""}`:loading?"در حال دریافت داده":"داده در دسترس نیست"}</div><button type="button" className="help-btn" onClick={()=>setShowHelp(!showHelp)}>{showHelp?"بستن راهنما":"❓ راهنمای استفاده"}</button></div></header>
 {message&&!live&&<div className="info">ℹ️ {message}</div>}
 <div className="meta"><span>آخرین بروزرسانی: {updated?new Date(updated).toLocaleString("fa-IR"):"—"}</span><div className="meta-btns"><button type="button" disabled={loading} onClick={load}>{loading?"در حال دریافت...":"بروزرسانی"}</button></div></div>
 <section className="section"><h2 className="section-title">💎 ارزهای اصلی بازار</h2><div className="majors-grid">{majors.length===0&&!loading&&<div className="muted">داده‌ای دریافت نشد.</div>}{majors.map(m=><div className="major-chip" key={m.symbol}><b>{m.symbol.replace("/USDT","")}</b><span className="price">{fmt(m.price)}</span><strong className={m.changePct>=0?"up":"down"}>{m.changePct>=0?"+":""}{m.changePct.toFixed(2)}%</strong></div>)}</div></section>
 <section className="section"><h2 className="section-title">📊 نمای کلی بازار</h2><div className="overview"><div className="ov-card"><h3>بیشترین رشد ۲۴س</h3><ul>{gainers.slice(0,5).map(g=><li key={g.symbol}><span>{g.symbol}</span><strong className="up">+{g.changePct.toFixed(1)}%</strong></li>)}{gainers.length===0&&<li className="muted">داده‌ای نیست</li>}</ul></div><div className="ov-card"><h3>بیشترین افت ۲۴س</h3><ul>{losers.slice(0,5).map(g=><li key={g.symbol}><span>{g.symbol}</span><strong className="down">{g.changePct.toFixed(1)}%</strong></li>)}{losers.length===0&&<li className="muted">داده‌ای نیست</li>}</ul></div><div className="ov-card"><h3>🚀 Pump Watch</h3><ul>{pumps.slice(0,10).map(p=><li key={p.symbol}><span>{p.symbol}</span><strong className="up">+{p.changePct.toFixed(1)}%</strong></li>)}{pumps.length===0&&<li className="muted">مورد غیرعادی یافت نشد</li>}</ul><p className="note">Pump ≠ BUY — فقط پایش با ریسک بالا</p></div></div></section>
 {risks.length>0&&signalFilter==="ALL"&&<section className="section"><h2 className="section-title">⚠️ هشدار ریسک / فروش</h2><div className="risk-row">{risks.slice(0,8).map(o=><div className="risk-chip" key={o.symbol}><b>{o.symbol}</b><span>{catLabel[o.category||o.action]||o.action}</span></div>)}</div></section>}
 <section className="section"><div className="section-head"><h2 className="section-title" style={{margin:0}}>{signalFilter==="BUY"?"🟢 سیگنال‌های خرید":signalFilter==="SELL"?"🔴 سیگنال‌های فروش":"🔥 فرصت‌های رتبه‌بندی‌شده"}</h2><div className="signal-btns"><button type="button" className={signalFilter==="ALL"?"sig active":"sig"} onClick={()=>setSignalFilter("ALL")}>همه ({items.length})</button><button type="button" className={signalFilter==="BUY"?"sig buy active":"sig buy"} onClick={()=>setSignalFilter("BUY")}>🟢 خرید ({buySignals.length})</button><button type="button" className={signalFilter==="SELL"?"sig active":"sig"} onClick={()=>setSignalFilter("SELL")}>🔴 فروش ({sellSignals.length})</button></div></div>{displayed.length===0?<div className="muted">{loading?"در حال دریافت داده‌های تبدیل...":"هنوز فرصتی از داده‌های زنده دریافت نشده است."}</div>:<div className="opps">{displayed.slice(0,24).map(o=><article className="opp-card" key={`${o.symbol}-${o.category}`}><div><b>{o.symbol}</b><span>{catLabel[o.category||o.action]||o.action}</span></div><strong>امتیاز {o.score}</strong><p>قیمت: {fmt(o.price)} · تغییر: {o.changePct==null?"—":`${o.changePct.toFixed(2)}%`}</p></article>)}</div>}</section>
 {showHelp&&<section className="help-box"><h2>📖 راهنمای استفاده</h2><p>داده‌ها از مسیرهای زنده تبدیل دریافت می‌شوند. اگر یک سرویس کند یا قطع باشد، داشبورد بعد از Timeout متوقف نمی‌ماند و خطای واقعی را نمایش می‌دهد.</p></section>}
 </div></main>}
